version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      - REDIS_HOST=redis
    depends_on:
      - postgres
      - redis
    restart: always

  redis:
    container_name: redis
    image: redis:latest
    expose:
      - '6379'
    ports:
      - "6379:6379"


  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: